site_name: Echarts 地图

nav:
  - 主页: index.md
  - 工具:
    - geojson 在线编辑器: tools/geojson-io.md
    - 地图整形器（mapshaper）: tools/mapshaper.md
    - 地图工匠（mapmaker）: tools/mapmaker.md
    - 地理空间数据格式翻译家 (GDAL): tools/gdal.md
  - 实战:
    - 提取北京市的轮廓: dissolve-internal-borders.md
    - 给天津市补上蓟洲区: add-ji-zhou-qu-to-tianjin.md
    - 瑞士在哪里？使用 natural earth 的地图: switzerland.md
  - 维护地图:
    - 把瑞士加入 echarts-countries-js 里: add-switzerland.md

docs_dir: book
site_dir: docs
