site_name: 给 Echarts 做地图
repo_url: https://github.com/echarts-maps/echarts-geomapping-book-zh
edit_uri: edit/master/book/


nav:
  - 主页: index.md
  - 工具:
    - geojson 在线编辑器: tools/geojson-io.md
    - 地图整形器（mapshaper）: tools/mapshaper.md
    - 地图工匠（mapmaker）: tools/mapmaker.md
    - 地理空间数据格式翻译家 (GDAL): tools/gdal.md
  - 简易制图:
    - 提取北京市的轮廓: howtos/dissolve-internal-borders.md
    - 县级地图是从哪里来的: howtos/split-geojson.md  
    - 给和田地区镶上昆玉市: howtos/encapsulated-shapes.md
  - 制图进阶:
    - 给天津市补上蓟洲区: howtos/add-ji-zhou-qu-to-tianjin.md
    - 瑞士在哪里？使用 natural earth 的地图: howtos/switzerland.md


docs_dir: book
site_dir: docs
