site_name: Echarts 地图

nav:
  - 主页: index.md
  - 工具:
    - geojson 在线编辑器: geojson-io.md
    - 地图整形器（mapshaper）: mapshaper.md
    - 地图工匠（mapmaker）: mapmaker.md
  - 实战:
    - 提取北京市的轮廓: dissolve-internal-borders.md
    - 给天津市补上蓟洲区: add-ji-zhou-qu-to-tianjin.md

docs_dir: book
site_dir: docs
